[package]
name = "hdf5-types"
version = "0.7.1"  # !V
authors = ["Ivan Smirnov <i.s.smirnov@gmail.com>"]
keywords = ["hdf5"]
license = "MIT OR Apache-2.0"
description = "Native Rust equivalents of HDF5 types."
repository = "https://github.com/aldanor/hdf5-rust"
homepage = "https://github.com/aldanor/hdf5-rust"
edition = "2018"

[features]
const_generics = []

[dependencies]
hdf5-sys = { path = "../hdf5-sys" }
ascii = "1.0"
libc = "0.2"

[dev-dependencies]
quickcheck = { version = "1.0", default-features = false }
